
title: ops n pops
email: contact@opsnpops.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog from a devops that has been quiet for too many times
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.opsnpops.io" # the base hostname & protocol for your site, e.g. http://example.com
domain: blog.opsnpops.io
github_username:  alexissellier

remote_theme: startbootstrap/startbootstrap-clean-blog-jekyll
plugins:
  - jekyll-feed
